#!/usr/bin/env python
def start():
    import sys
    import subprocess
    import time
    subprocess.Popen(["sh", "compile"])
    s = "java -cp .:../external/*:../external/boofcv/*:ab/demo/ ab/demo/MainEntry -nasc".split()
    print "[2/3] Server is started."
    subprocess.Popen(s)
    print "[3/3] Client started."

start()
